version: 2

models:
  - name: stg_sheets__customers
  - name: stg_sheets__employees
  - name: stg_harvest__uninvoiced
  - name: stg_harvest__task_assignments_task
  - name: stg_harvest__invoice_payments_payment_gateway
  - name: stg_harvest__invoice_payments
  - name: stg_harvest__clients
  - name: stg_harvest__projects_client
  - name: stg_harvest__invoice_item_categories
  - name: stg_harvest__billable_rates
  - name: stg_harvest__time_entries_user
  - name: stg_harvest__expenses_categories
  - name: stg_harvest__expenses_user
  - name: stg_harvest__time_entries_client
  - name: stg_harvest__contacts
  - name: stg_harvest__expenses_invoice
  - name: stg_harvest__estimates_creator
  - name: stg_harvest__expenses_expense_category
  - name: stg_harvest__users
  - name: stg_harvest__project_assignments_task_assignments_task
  - name: stg_harvest__project_assignments_task_assignments
  - name: stg_harvest__time_entries
  - name: stg_harvest__estimate_item_categories
  - name: stg_harvest__time_entries_project
  - name: stg_harvest__estimate_messages_recipients
  - name: stg_harvest__estimates
  - name: stg_harvest__time_team
  - name: stg_harvest__time_clients
  - name: stg_harvest__expenses_receipt
  - name: stg_harvest__project_assignments_project
  - name: stg_harvest__estimate_messages
  - name: stg_harvest__user_assignments_project
  - name: stg_harvest__roles
  - name: stg_harvest__expenses_project
  - name: stg_harvest__time_entries_task_assignment
  - name: stg_harvest__project_budget
  - name: stg_harvest__invoices_line_items_project
  - name: stg_harvest__company
  - name: stg_harvest__time_tasks
  - name: stg_harvest__project_assignments_client
  - name: stg_harvest__expenses_clients
  - name: stg_harvest__user_assignments_user
  - name: stg_harvest__cost_rates
  - name: stg_harvest__invoices
  - name: stg_harvest__expense_categories
  - name: stg_harvest__invoices_line_items
  - name: stg_harvest__tasks
  - name: stg_harvest__time_projects
  - name: stg_harvest__expenses_client
  - name: stg_harvest__time_entries_user_assignment
  - name: stg_harvest__contacts_client
  - name: stg_harvest__task_assignments
  - name: stg_harvest__project_assignments
  - name: stg_harvest__task_assignments_project
  - name: stg_harvest__invoices_creator
  - name: stg_harvest__invoices_client
  - name: stg_harvest__invoice_messages
  - name: stg_harvest__time_entries_task
  - name: stg_harvest__expenses_user_assignment
  - name: stg_harvest__user_assignments
  - name: stg_harvest__estimates_client
  - name: stg_harvest__expenses_projects
  - name: stg_harvest__expenses_team
  - name: stg_harvest__time_entries_invoice
  - name: stg_harvest__invoice_messages_recipients
  - name: stg_harvest__expenses
  - name: stg_harvest__projects